### ISSUE TITLE
Can not raid Online's Castle

### ISSUE THREAD

**Issue by tamto6666** [SkyTech6/OfflineRaidGuard#3]
![image](https://github.com/SkyTech6/OfflineRaidGuard/assets/107444722/d294f977-2e92-40db-985b-dc2067610583)
It said "Need Golem to raid" but I'm already on Golem

**Comment by SkyTech6** [comment]
And the person was online? lol that's unfortunate. Could you share your OutputLog.txt?

**Comment by SkyTech6** [comment]
Also please update to v0.1.5 that can be found in the Releases

**Comment by tamto6666** [comment]
> And the person was online? lol that's unfortunate. Could you share your OutputLog.txt?
> 
> That's what it should say if they were offline

yes ther're Online

will test with 0.1.5 again
